DROP TABLE customer CASCADE;
DROP TABLE location CASCADE;
DROP TABLE ordering CASCADE;
DROP TABLE request CASCADE;
DROP TABLE request_condition;
DROP TABLE good;
DROP TABLE courier CASCADE;
DROP TABLE courier_order;
DROP TYPE dimensions;
DROP TYPE good_status;
DROP TYPE order_status;
DROP TYPE extra_condition;